/* Populated by react-webpack-redux:action */

export const SELECT_BOOK = 'SELECT_BOOK';
export const CREATE_FEEDBACK_SUCCESS = 'CREATE_FEEDBACK_SUCCESS';
export const FEEDBACK_DETAILS = 'FEEDBACK_DETAILS';
export const EDIT_FEEDBACK = 'EDIT_FEEDBACK';
export const LOAD_FEEDBACKS_SUCCESS = 'LOAD_FEEDBACKS_SUCCESS';
export const LOAD_BOOKS_SUCCESS = 'LOAD_BOOKS_SUCCESS';
export const GET_BOOK_BY_ID_SUCCESS = 'GET_BOOK_BY_ID_SUCCESS';
export const GET_FEEDBACK_BY_ID_SUCCESS = 'GET_FEEDBACK_BY_ID_SUCCESS';
export const EDIT_FEEDBACK_SUCCESS = 'EDIT_FEEDBACK_SUCCESS';
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';


export const CREATE_POSITION = 'CREATE_POSITION';
export const EDIT_POSITION = 'EDIT_POSITION';
