/* Populated by react-webpack-redux:action */

export const SELECT_BOOK = 'SELECT_BOOK';
export const CREATE_FEEDBACK_SUCCESS = 'CREATE_FEEDBACK_SUCCESS';
export const FEEDBACK_DETAILS = 'FEEDBACK_DETAILS';
export const EDIT_FEEDBACK = 'EDIT_FEEDBACK';
export const LOAD_FEEDBACKS_SUCCESS = 'LOAD_FEEDBACKS_SUCCESS';
export const LOAD_FEEDBACKS_FAILURE = 'LOAD_FEEDBACKS_FAILURE';
export const LOAD_CANDIDATES_SUCCESS = 'LOAD_CANDIDATES_SUCCESS';
export const LOAD_CANDIDATES_FAILURE = 'LOAD_CANDIDATES_FAILURE';
export const LOAD_POSITIONS_SUCCESS = 'LOAD_POSITIONS_SUCCESS';
export const LOAD_POSITIONS_FAILURE = 'LOAD_POSITIONS_FAILURE';
export const LOAD_BOOKS_SUCCESS = 'LOAD_BOOKS_SUCCESS';
export const LOAD_BOOKS_FAILURE = 'LOAD_BOOKS_FAILURE';
export const GET_BOOK_BY_ID_SUCCESS = 'GET_BOOK_BY_ID_SUCCESS';
export const GET_BOOK_BY_ID_FAILURE = 'GET_BOOK_BY_ID_FAILURE';
export const GET_FEEDBACK_BY_ID_SUCCESS = 'GET_FEEDBACK_BY_ID_SUCCESS';
export const GET_FEEDBACK_BY_ID_FAILURE = 'GET_FEEDBACK_BY_ID_FAILURE';
export const EDIT_FEEDBACK_SUCCESS = 'EDIT_FEEDBACK_SUCCESS';
export const EDIT_FEEDBACK_FAILURE = 'EDIT_FEEDBACK_FAILURE';
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';


export const CREATE_POSITION_SUCCESS = 'CREATE_POSITION_SUCCESS';
export const EDIT_POSITION_SUCCESS = 'EDIT_POSITION_SUCCESS';
export const CREATE_POSITION_FAILURE = 'CREATE_POSITION_FAILURE';
export const EDIT_POSITION_FAILURE = 'EDIT_POSITION_FAILURE';
export const GET_POSITION_BY_ID_SUCCESS = 'GET_POSITION_BY_ID_SUCCESS';
export const GET_POSITION_BY_ID_FAILURE = 'GET_POSITION_BY_ID_FAILURE';
